FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Application code
COPY app.py agent.py ./

# Model artifacts: classifiers, knowledge-base embeddings, and the index itself.
# These are generated by the pipeline (see data_pipeline/ and training/ in the
# README) and are not stored in git due to size - place them here before
# building the image.
COPY category_classifier_embeddings.joblib .
COPY priority_classifier_embeddings.joblib .
COPY kb_embeddings.npy .
COPY kb_with_index.csv .

EXPOSE 8000

# API keys are passed at container run time, not baked into the image:
# docker run -e VOYAGE_API_KEY=... -e ANTHROPIC_API_KEY=... -p 8000:8000 customer-support-agent
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
